<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SociosSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'numero_socio' => 'ASN0001',
                'dni' => '12345678',
                'nombre' => 'María Elena',
                'apellido' => 'González',
                'email' => 'maria.gonzalez@email.com',
                'telefono' => '+54 9 264 123 4567',
                'domicilio' => 'Av. San Martín 1234, Capital, San Juan',
                'fecha_nacimiento' => '1985-03-15',
                'fecha_ingreso' => '2020-01-15',
                'estado' => 'activo',
                'tipo_socio' => 'titular',
                'universidad' => 'Universidad Nacional de San Juan',
                'matricula_profesional' => 'MP001234',
                'fecha_graduacion' => '2008-12-15',
                'observaciones' => 'Especialista en nutrición deportiva',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'numero_socio' => 'ASN0002',
                'dni' => '23456789',
                'nombre' => 'Carlos Alberto',
                'apellido' => 'López',
                'email' => 'carlos.lopez@email.com',
                'telefono' => '+54 9 264 234 5678',
                'domicilio' => 'Calle Libertad 567, Rivadavia, San Juan',
                'fecha_nacimiento' => '1980-07-22',
                'fecha_ingreso' => '2019-05-10',
                'estado' => 'activo',
                'tipo_socio' => 'titular',
                'universidad' => 'Universidad Católica de Cuyo',
                'matricula_profesional' => 'MP002345',
                'fecha_graduacion' => '2005-07-20',
                'observaciones' => 'Especialista en nutrición clínica',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'numero_socio' => 'ASN0003',
                'dni' => '34567890',
                'nombre' => 'Ana Sofía',
                'apellido' => 'Martínez',
                'email' => 'ana.martinez@email.com',
                'telefono' => '+54 9 264 345 6789',
                'domicilio' => 'Barrio Villa Krause, Rawson, San Juan',
                'fecha_nacimiento' => '1992-11-08',
                'fecha_ingreso' => '2021-03-22',
                'estado' => 'activo',
                'tipo_socio' => 'adherente',
                'universidad' => 'Universidad Nacional de San Juan',
                'matricula_profesional' => 'MP003456',
                'fecha_graduacion' => '2016-03-10',
                'observaciones' => 'Nutrición infantil y materna',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'numero_socio' => 'ASN0004',
                'dni' => '45678901',
                'nombre' => 'Luis Fernando',
                'apellido' => 'Rodríguez',
                'email' => 'luis.rodriguez@email.com',
                'telefono' => '+54 9 264 456 7890',
                'domicilio' => 'Av. Córdoba 890, Santa Lucía, San Juan',
                'fecha_nacimiento' => '1995-02-14',
                'fecha_ingreso' => '2023-01-08',
                'estado' => 'activo',
                'tipo_socio' => 'estudiante',
                'universidad' => 'Universidad Nacional de San Juan',
                'matricula_profesional' => null,
                'fecha_graduacion' => null,
                'observaciones' => 'Estudiante de 5º año',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'numero_socio' => 'ASN0005',
                'dni' => '56789012',
                'nombre' => 'Patricia Isabel',
                'apellido' => 'Fernández',
                'email' => 'patricia.fernandez@email.com',
                'telefono' => '+54 9 264 567 8901',
                'domicilio' => 'Calle Mendoza 456, Chimbas, San Juan',
                'fecha_nacimiento' => '1988-09-30',
                'fecha_ingreso' => '2018-11-15',
                'estado' => 'inactivo',
                'tipo_socio' => 'titular',
                'universidad' => 'Universidad del Aconcagua',
                'matricula_profesional' => 'MP004567',
                'fecha_graduacion' => '2012-12-20',
                'observaciones' => 'Actualmente en pausa por motivos personales',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'numero_socio' => 'ASN0006',
                'dni' => '67890123',
                'nombre' => 'Roberto Miguel',
                'apellido' => 'Silva',
                'email' => 'roberto.silva@email.com',
                'telefono' => '+54 9 264 678 9012',
                'domicilio' => 'Barrio Universitario, Capital, San Juan',
                'fecha_nacimiento' => '1975-12-05',
                'fecha_ingreso' => '2015-06-01',
                'estado' => 'suspendido',
                'tipo_socio' => 'titular',
                'universidad' => 'Universidad Nacional de Córdoba',
                'matricula_profesional' => 'MP005678',
                'fecha_graduacion' => '2000-06-15',
                'observaciones' => 'Suspendido por falta de pago de cuotas',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'numero_socio' => 'ASN0007',
                'dni' => '78901234',
                'nombre' => 'Carmen Rosa',
                'apellido' => 'Pérez',
                'email' => 'carmen.perez@email.com',
                'telefono' => '+54 9 264 789 0123',
                'domicilio' => 'Villa Mercedes, Capital, San Juan',
                'fecha_nacimiento' => '1990-04-18',
                'fecha_ingreso' => '2022-08-12',
                'estado' => 'activo',
                'tipo_socio' => 'adherente',
                'universidad' => 'Universidad Nacional de San Juan',
                'matricula_profesional' => 'MP006789',
                'fecha_graduacion' => '2014-08-25',
                'observaciones' => 'Especialista en nutrición geriátrica',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'numero_socio' => 'ASN0008',
                'dni' => '89012345',
                'nombre' => 'Diego Alejandro',
                'apellido' => 'Morales',
                'email' => 'diego.morales@email.com',
                'telefono' => '+54 9 264 890 1234',
                'domicilio' => 'Pocito, San Juan',
                'fecha_nacimiento' => '1996-01-27',
                'fecha_ingreso' => '2024-01-10',
                'estado' => 'activo',
                'tipo_socio' => 'estudiante',
                'universidad' => 'Universidad Católica de Cuyo',
                'matricula_profesional' => null,
                'fecha_graduacion' => null,
                'observaciones' => 'Estudiante de 4º año, presidente del centro de estudiantes',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'numero_socio' => 'ASN0009',
                'dni' => '90123456',
                'nombre' => 'Valeria Beatriz',
                'apellido' => 'Castro',
                'email' => 'valeria.castro@email.com',
                'telefono' => '+54 9 264 901 2345',
                'domicilio' => 'San Martín, San Juan',
                'fecha_nacimiento' => '1983-06-12',
                'fecha_ingreso' => '2017-04-05',
                'estado' => 'activo',
                'tipo_socio' => 'titular',
                'universidad' => 'Universidad Nacional de San Juan',
                'matricula_profesional' => 'MP007890',
                'fecha_graduacion' => '2007-12-10',
                'observaciones' => 'Nutricionista en hospital público',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'numero_socio' => 'ASN0010',
                'dni' => '01234567',
                'nombre' => 'Fernando José',
                'apellido' => 'Vega',
                'email' => 'fernando.vega@email.com',
                'telefono' => '+54 9 264 012 3456',
                'domicilio' => 'Caucete, San Juan',
                'fecha_nacimiento' => '1987-10-03',
                'fecha_ingreso' => '2019-12-20',
                'estado' => 'activo',
                'tipo_socio' => 'adherente',
                'universidad' => 'Universidad del Salvador',
                'matricula_profesional' => 'MP008901',
                'fecha_graduacion' => '2011-07-15',
                'observaciones' => 'Consulta privada y docente universitario',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        // Insert data
        $this->db->table('socios')->insertBatch($data);

        echo "Socios de prueba creados exitosamente.\n";
        echo "Total de socios insertados: " . count($data) . "\n";
        echo "Estados: Activos (7), Inactivos (1), Suspendidos (1)\n";
        echo "Tipos: Titulares (5), Adherentes (3), Estudiantes (2)\n";
    }
}